# Generated by Django 4.0.5 on 2022-07-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0005_email_key_email_request_email_seen_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='key',
        ),
        migrations.RemoveField(
            model_name='email',
            name='request',
        ),
        migrations.RemoveField(
            model_name='email',
            name='seen_at',
        ),
    ]
